echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Devops"
echo "I am learning git"
echo "this is aamir"
echo "today is 7th March"
echo "today is saturday"
echo "git stash demo"
echo "have a nice day"
echo "this is second stash demo"
echo "today its very hot"
echo "today we are suppose to complete the devops practs"
echo "Pune"
echo "Mumbai"
echo "Delhi"