echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Devops"
echo "I am learning git"
echo "this is aamir"
echo "I am from batch 31"
echo "this is saturday"
echo "Saturday practical running"
echo "tomorrow is sunday"
echo "monday"
echo "tuesday"

